import { useEffect, useRef, useState } from "react";
import type { Bookmark, PlayerState, Video } from "../types";
import { clamp, formatTime } from "../lib/time";

type Props = { video: Video | null; bookmarks: Bookmark[]; seekStep: number; sidebarOpen: boolean; onToggleSidebar: () => void; onCreateBookmark: (timeMs: number) => void; onState: (videoId: string, state: PlayerState) => void; onMediaError: (message: string) => void; };

export function Player({ video, bookmarks, seekStep, sidebarOpen, onToggleSidebar, onCreateBookmark, onState, onMediaError }: Props) {
  const media = useRef<HTMLVideoElement>(null); const player = useRef<HTMLDivElement>(null); const interval = useRef<number | undefined>(undefined);
  const [duration, setDuration] = useState(0); const [time, setTime] = useState(0); const [playing, setPlaying] = useState(false); const [rate, setRate] = useState(1); const [mirrored, setMirrored] = useState(false); const [volume, setVolume] = useState(1); const [muted, setMuted] = useState(false); const [ready, setReady] = useState(false); const [error, setError] = useState("");
  const persist = (overrides: Partial<{ positionMs: number; playbackRate: number; mirrored: boolean; durationMs: number }> = {}) => { const v = media.current; if (video && v) onState(video.id, { positionMs: Math.round(v.currentTime * 1000), playbackRate: v.playbackRate, mirrored, ...overrides }); };
  useEffect(() => {
    setReady(false); setError(""); setDuration(0); setTime(0); setPlaying(false);
    setRate(video?.playbackRate ?? 1); setMirrored(video?.mirrored ?? false);
  }, [video?.id]);
  useEffect(() => () => { window.clearInterval(interval.current); media.current?.pause(); }, []);
  useEffect(() => () => {
    const v = media.current;
    if (v && video) {
      onState(video.id, { positionMs: Math.round(v.currentTime * 1000), playbackRate: v.playbackRate, mirrored, durationMs: Number.isFinite(v.duration) ? Math.round(v.duration * 1000) : undefined });
      v.pause();
    }
  }, [video?.id]);
  const metadata = () => { const v = media.current; if (!v || !video) return; v.playbackRate = clamp(video.playbackRate ?? 1, .25, 1.5); v.preservesPitch = true; v.currentTime = clamp((video.positionMs ?? 0) / 1000, 0, Number.isFinite(v.duration) ? v.duration : 0); setDuration(v.duration * 1000); setTime(v.currentTime * 1000); setReady(true); persist({ durationMs: Math.round(v.duration * 1000) }); };
  const togglePlay = async () => { const v = media.current; if (!v || !ready) return; try { if (v.paused) await v.play(); else v.pause(); } catch { setError("Playback was blocked. Click play to try again."); } };
  const seek = (delta: number) => { const v = media.current; if (!v || !ready) return; v.currentTime = clamp(v.currentTime + delta, 0, v.duration || 0); setTime(v.currentTime * 1000); persist(); };
  const setSpeed = (input: number) => { const next = clamp(Number.isFinite(input) ? input : 1, .25, 1.5); const v = media.current; if (v) v.playbackRate = next; setRate(next); persist({ playbackRate: next }); };
  const toggleMirror = () => { const next = !mirrored; setMirrored(next); persist({ mirrored: next }); };
  useEffect(() => { interval.current = window.setInterval(() => { const v = media.current; if (v && !v.paused) persist(); }, 5000); return () => window.clearInterval(interval.current); }, [video?.id, mirrored]);
  const missing = video?.missing;
  return <section className="player-area"><div className="player-title"><div>{video ? <><span className="eyebrow">Now practicing</span><h1>{video.displayName}</h1></> : <><span className="eyebrow">Your practice library</span><h1>Choose a video to begin</h1></>}</div><button className="icon-button" onClick={onToggleSidebar} aria-label={sidebarOpen ? "Hide bookmarks" : "Show bookmarks"}>☰ <span>Notes</span></button></div>
    <div className={`player-shell ${mirrored ? "mirrored" : ""}`} ref={player}>
      {video && !missing ? <video ref={media} src={`/api/videos/${encodeURIComponent(video.id)}/media`} preload="metadata" onLoadedMetadata={metadata} onTimeUpdate={() => { const v = media.current; if (v) setTime(v.currentTime * 1000); }} onSeeked={() => persist()} onPlay={() => setPlaying(true)} onPause={() => { setPlaying(false); persist(); }} onEnded={() => { setPlaying(false); persist({ positionMs: Math.round((media.current?.duration ?? 0) * 1000) }); }} onError={() => { const m = media.current; const msg = m?.error?.code === MediaError.MEDIA_ERR_SRC_NOT_SUPPORTED ? "This file could not be decoded by your browser. Try an MP4/H.264/AAC copy." : "Video loading failed. Check that the file is still available."; setError(msg); onMediaError(msg); }} /> : <div className="player-placeholder"><span>{missing ? "⌁" : "▶"}</span><p>{missing ? "The app-managed video file is missing." : "Select or import a local dance video."}</p>{missing && <p className="muted">Reimport the identical original file from the library.</p>}</div>}
      {error && <div className="media-error" role="alert">{error}</div>}
      {video && !missing && <div className="video-controls"><div className="timeline-row"><span>{formatTime(time)}</span><div className="timeline-wrap"><input aria-label="Video timeline" type="range" min="0" max={duration || 1} value={time} disabled={!ready} onChange={(e) => { const v = media.current; if (v) { v.currentTime = Number(e.target.value) / 1000; setTime(Number(e.target.value)); } }} onMouseUp={() => persist()} />{bookmarks.map((b) => <button key={b.id} className="marker" style={{ left: `${duration ? (b.timestampMs / duration) * 100 : 0}%` }} title={`${b.title} · ${formatTime(b.timestampMs, true)}`} aria-label={`Jump to ${b.title}`} onClick={() => { const v = media.current; if (v) { v.currentTime = b.timestampMs / 1000; setTime(b.timestampMs); persist(); } }} />)}</div><span>{formatTime(duration)}</span></div><div className="controls-row"><button aria-label={playing ? "Pause" : "Play"} className="play-button" disabled={!ready} onClick={togglePlay}>{playing ? "❚❚" : "▶"}</button><button disabled={!ready} aria-label={`Back ${seekStep} seconds`} onClick={() => seek(-seekStep)}>↶ <span>{seekStep}s</span></button><button disabled={!ready} aria-label={`Forward ${seekStep} seconds`} onClick={() => seek(seekStep)}>↷ <span>{seekStep}s</span></button><div className="control-spacer" /><button disabled={!ready} onClick={() => { const v = media.current; if (v) { const timestampMs = Math.round(v.currentTime * 1000); v.pause(); onCreateBookmark(timestampMs); } }}>＋ Bookmark</button><button className={mirrored ? "toggled" : ""} disabled={!ready} onClick={toggleMirror} aria-label="Toggle mirror">↔ Mirror</button><label className="speed-control">Speed<input aria-label="Playback speed" type="number" min=".25" max="1.5" step=".01" value={rate.toFixed(2)} disabled={!ready} onChange={(e) => setSpeed(Number(e.target.value))} /><span>×</span></label><input className="volume" aria-label="Volume" type="range" min="0" max="1" step=".01" value={muted ? 0 : volume} onChange={(e) => { const val = Number(e.target.value); if (media.current) { media.current.volume = val; media.current.muted = val === 0; } setVolume(val); setMuted(val === 0); }} /><button aria-label="Mute" disabled={!ready} onClick={() => { const next = !muted; if (media.current) media.current.muted = next; setMuted(next); }}> {muted ? "Unmute" : "Mute"} </button><button aria-label="Fullscreen" disabled={!ready} onClick={() => player.current?.requestFullscreen?.()}>⛶</button></div></div>}
    </div><p className="shortcuts"><kbd>Space</kbd> play/pause <kbd>←</kbd><kbd>→</kbd> seek <kbd>B</kbd> bookmark <kbd>M</kbd> mirror</p>
  </section>;
}
