import { useCallback, useEffect, useRef, useState } from "react";
import { api } from "./api";
import { Bookmarks } from "./components/Bookmarks";
import { Library } from "./components/Library";
import { Player } from "./components/Player";
import { isTypingTarget } from "./lib/time";
import type { Bookmark, Settings, Video } from "./types";

type Draft = { timestampMs: number; title: string; description: string };

export default function App() {
  const [videos, setVideos] = useState<Video[]>([]); const [active, setActive] = useState<Video | null>(null); const [bookmarks, setBookmarks] = useState<Bookmark[]>([]); const [settings, setSettings] = useState<Settings>({ seekStepSeconds: 1 }); const [draft, setDraft] = useState<Draft | null>(null); const [sidebarOpen, setSidebarOpen] = useState(true); const [importing, setImporting] = useState<number | null>(null); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true); const [settingsOpen, setSettingsOpen] = useState(false); const importBackup = useRef<HTMLInputElement>(null);
  const show = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 6000); };
  const load = useCallback(async () => { try { const [all, prefs] = await Promise.all([api.videos(), api.settings()]); setVideos(all); setSettings(prefs); const selected = all.find((v) => v.id === prefs.lastVideoId) ?? all[0] ?? null; setActive(selected); } catch (e) { show((e as Error).message || "Could not reach LindyLoop."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    let cancelled = false;
    if (!active) { setBookmarks([]); return () => { cancelled = true; }; }
    setBookmarks([]);
    void api.updateSettings({ lastVideoId: active.id }).then((next) => { if (!cancelled) setSettings(next); }).catch(() => undefined);
    api.bookmarks(active.id).then((next) => { if (!cancelled) setBookmarks(next); }).catch((e) => { if (!cancelled) show(`Could not load bookmarks: ${(e as Error).message}`); });
    return () => { cancelled = true; };
  }, [active?.id]);
  const select = (video: Video) => { setDraft(null); setActive(video); };
  const importVideo = async (file: File) => { setImporting(0); try { const created = await api.createVideo(file, setImporting); setVideos((items) => [created, ...items]); select(created); show("Video imported into the local library."); } catch (e) { show((e as Error).message); } finally { setImporting(null); } };
  const updateActive = (updated: Video) => { setVideos((all) => all.map((v) => v.id === updated.id ? updated : v)); if (active?.id === updated.id) setActive(updated); };
  const deleteVideo = async (video: Video) => { if (!window.confirm(`Delete “${video.displayName}” from LindyLoop? Its app-managed copy and all bookmarks will be removed. The source file is untouched.`)) return; try { await api.deleteVideo(video.id); setVideos((all) => all.filter((v) => v.id !== video.id)); if (active?.id === video.id) setActive(null); show("Video deleted."); } catch (e) { show((e as Error).message); } };
  const createDraft = (timestampMs: number) => setDraft({ timestampMs, title: `Bookmark at ${new Date(timestampMs).toISOString().slice(14, 23).replace(".", ".")}`, description: "" });
  const saveDraft = async (next: Draft) => { if (!active) return; const created = await api.createBookmark(active.id, next); setBookmarks((all) => [...all, created].sort((a, b) => a.timestampMs - b.timestampMs || a.createdAt.localeCompare(b.createdAt))); setDraft(null); };
  const updateBookmark = async (bookmark: Bookmark, patch: Partial<Draft>) => { try { const updated = await api.updateBookmark(bookmark.id, patch); setBookmarks((all) => all.map((b) => b.id === updated.id ? updated : b)); } catch (e) { show(`Bookmark not saved: ${(e as Error).message}`); throw e; } };
  const removeBookmark = async (bookmark: Bookmark) => { if (!window.confirm(`Delete bookmark “${bookmark.title}”?`)) return; try { await api.deleteBookmark(bookmark.id); setBookmarks((all) => all.filter((b) => b.id !== bookmark.id)); } catch (e) { show((e as Error).message); } };
  const jump = (bookmark: Bookmark) => { const video = document.querySelector("video"); if (video) video.currentTime = bookmark.timestampMs / 1000; };
  const updateSettings = async (seekStepSeconds: number) => { if (!Number.isFinite(seekStepSeconds) || seekStepSeconds < .1 || seekStepSeconds > 60) return; const next = await api.updateSettings({ seekStepSeconds }); setSettings(next); };
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.isComposing || isTypingTarget(event.target)) return; const video = document.querySelector("video"); if (!video || !active) return; if (event.key === " ") { event.preventDefault(); video.paused ? void video.play() : video.pause(); } else if (event.key === "ArrowLeft" || event.key === "ArrowRight") { event.preventDefault(); video.currentTime = Math.max(0, Math.min(video.duration || 0, video.currentTime + (event.key === "ArrowLeft" ? -settings.seekStepSeconds : settings.seekStepSeconds))); } else if (event.key.toLowerCase() === "b") { event.preventDefault(); video.pause(); createDraft(Math.round(video.currentTime * 1000)); } else if (event.key.toLowerCase() === "m") { event.preventDefault(); document.querySelector<HTMLButtonElement>("button[aria-label='Toggle mirror']")?.click(); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [active?.id, settings.seekStepSeconds]);
  const backup = async () => { try { const blob = await api.exportMetadata(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "lindyloop-metadata.json"; link.click(); URL.revokeObjectURL(url); show("Metadata exported. Your video files are not included."); } catch (e) { show((e as Error).message); } };
  return <main className="app-shell"><Library videos={videos} activeId={active?.id} importing={importing} onSelect={select} onImport={importVideo} onReimport={(video, file) => void api.reimport(video.id, file).then(updateActive).then(() => show("Original video reconnected.")).catch((e) => show((e as Error).message))} onRename={(video, displayName) => void api.updateVideo(video.id, { displayName }).then(updateActive).catch((e) => show((e as Error).message))} onDelete={deleteVideo} />
    <div className="workspace">{loading ? <div className="loading">Opening your library…</div> : <Player video={active} bookmarks={bookmarks} seekStep={settings.seekStepSeconds} sidebarOpen={sidebarOpen} onToggleSidebar={() => setSidebarOpen(!sidebarOpen)} onCreateBookmark={createDraft} onState={(videoId, state) => { void api.playerState(videoId, state).then(updateActive).catch(() => undefined); }} onMediaError={show} />}</div>
    {sidebarOpen && <Bookmarks bookmarks={bookmarks} draft={draft} durationMs={active?.durationMs ?? 0} onCancelDraft={() => setDraft(null)} onSaveDraft={saveDraft} onJump={jump} onUpdate={updateBookmark} onDelete={removeBookmark} />}
    <button className="settings-fab" aria-label="Open settings" onClick={() => setSettingsOpen(true)}>⚙</button>
    {settingsOpen && <div className="dialog-backdrop" role="presentation" onMouseDown={() => setSettingsOpen(false)}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="settings-heading" onMouseDown={(e) => e.stopPropagation()}><div className="dialog-head"><h2 id="settings-heading">Settings</h2><button onClick={() => setSettingsOpen(false)} aria-label="Close settings">×</button></div><label className="field">Seek step (seconds)<input type="number" min=".1" max="60" step=".1" value={settings.seekStepSeconds} onChange={(e) => void updateSettings(Number(e.target.value)).catch((error) => show(error.message))} /><small>Used by the seek buttons and Left/Right keys.</small></label><hr /><h3>Metadata backup</h3><p>Export saves library details and bookmarks, not video files. For a complete backup, quit LindyLoop and copy its data folder.</p><div className="dialog-actions"><button onClick={backup}>Export metadata</button><input ref={importBackup} className="sr-only" type="file" accept="application/json,.json" onChange={async (e) => { const file = e.target.files?.[0]; if (!file) return; try { const result = await api.importMetadata(file); show(`Imported ${result.imported}; skipped ${result.skipped} existing records.`); await load(); } catch (error) { show((error as Error).message); } }} /><button onClick={() => importBackup.current?.click()}>Import metadata</button></div><p className="storage-note">Video copies live in LindyLoop’s local application-support data folder.</p></section></div>}
    {notice && <div className="toast" role="status">{notice}</div>}
  </main>;
}
